### PR TITLE
Update to support modeltranslation 0.4.0

### PR DESCRIPTION
**Pull request by apollovy**
Hello. Version in your repo is for modeltranslation 0.3.3. In 0.4.0 they changed html classes.
By apollovy apollovy@gmail.com'

### CODE REVIEW

**Comment by jacobsvante** [comment]
Good find apollov! This doesn't seem to apply to the latest release available on PyPi (0.4.0-beta2) though so I added support for both CSS-classes.

**Comment by apollovy** [comment]
Feels strange, but
    http://pypi.python.org/pypi/django-modeltranslation/0.4.0
is not beta for now. Though it's cool that both versions now supported.

**Comment by jacobsvante** [comment]
Weird, I couldnt' find any newer version

```
air:~ jacob$ pip search django-modeltranslation
django-modeltranslation   - Translates Django models using a registration
                            approach.
  INSTALLED: 0.4.0-beta2 (latest)
```

**Comment by apollovy** [comment]
(venv)apollov@apollov-work:$ pip freeze | grep modeltranslation
django-modeltranslation==0.4.0

=)
13.11.2012 17:40, Jacob Magnusson пишет:

**Comment by apollovy** [comment]
Byt the way! Is X.X.X-beta earlier than X.X.X??
I'm not sure (maybe pip is not installing -beta packages when you type `pip install foo`), but, AFAIK, X.X.X-beta version is less in pip understanding than X.X.X, and that may be a bug in `pip search`...

**Comment by jacobsvante** [comment]
Seems that pip ranks `x.x.x-beta2` higher thank `x.x.x`. Try this:

```
pip install -U django-modeltranslation==0.4.0
pip install -U django-modeltranslation
```

It installs 0.4.0-beta2

**Comment by jacobsvante** [comment]
I created an issue about it:

https://github.com/deschler/django-modeltranslation/issues/103

**Comment by apollovy** [comment]
`
(venv)apollov@apollov-work:~$ pip install -U django-modeltranslation
Downloading/unpacking django-modeltranslation
   Downloading django-modeltranslation-0.4.0.tar.gz
   Running setup.py egg_info for package django-modeltranslation

Installing collected packages: django-modeltranslation
   Found existing installation: django-modeltranslation 0.4.0
     Uninstalling django-modeltranslation:
       Successfully uninstalled django-modeltranslation
   Running setup.py install for django-modeltranslation

Successfully installed django-modeltranslation
Cleaning up...
`
Interesting...
13.11.2012 18:25, Jacob Magnusson пишет:

**Comment by jacobsvante** [comment]
What does `$ pip --version` give you?

**Comment by apollovy** [comment]
pip 1.0.2 from 
/home/apollov/venv/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg 
(python 2.7)
13.11.2012 18:31, Jacob Magnusson пишет:

**Comment by jacobsvante** [comment]
Okay try:

```
pip install -U pip
pip install -U django-modeltranslation
```

Does it still give you 0.4.0?

**Comment by apollovy** [comment]
`
(venv)apollov@apollov-work:~$ pip install -U pip
Downloading/unpacking pip
   Downloading pip-1.2.1.tar.gz (102Kb): 102Kb downloaded
   Running setup.py egg_info for package pip

```
 warning: no files found matching '*.html' under directory 'docs'
 warning: no previously-included files matching '*.txt' found under 
```

directory 'docs/_build'
     no previously-included directories found matching 
'docs/_build/_sources'
Installing collected packages: pip
   Found existing installation: pip 1.0.2
     Uninstalling pip:
       Successfully uninstalled pip
   Running setup.py install for pip

```
 warning: no files found matching '*.html' under directory 'docs'
 warning: no previously-included files matching '*.txt' found under 
```

directory 'docs/_build'
     no previously-included directories found matching 
'docs/_build/_sources'
     Installing pip script to /home/apollov/venv/bin
     Installing pip-2.7 script to /home/apollov/venv/bin
Successfully installed pip
Cleaning up...
(venv)apollov@apollov-work:~$ pip install -U django-modeltranslation
Requirement already up-to-date: django-modeltranslation in 
./venv/lib/python2.7/site-packages
Cleaning up...
(venv)apollov@apollov-work:~$ pip --version
pip 1.2.1 from /home/apollov/venv/lib/python2.7/site-packages (python 2.7)
(venv)apollov@apollov-work:~$ pip freeze | grep modeltranslation
django-modeltranslation==0.4.0
`
No effect...
13.11.2012 18:33, Jacob Magnusson пишет:

> |pip install -U pip
> pip install -U django-modeltranslation
> |

**Comment by jacobsvante** [comment]
Okay one final:

```
pip install uninstall django-modeltranslation && pip install django-modeltranslation
```

**Comment by apollovy** [comment]
1
(venv)apollov@apollov-work:~$ pip uninstall django-modeltranslation && 
pip install django-modeltranslation
Uninstalling django-modeltranslation:
/home/apollov/venv/lib/python2.7/site-packages/django_modeltranslation-0.4.0-py2.7.egg-info
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/**init**.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/**init**.pyc
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/admin.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/admin.pyc
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/fields.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/fields.pyc
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/management/**init**.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/management/**init**.pyc
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/management/commands/**init**.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/management/commands/**init**.pyc
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/management/commands/sync_translation_fields.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/management/commands/sync_translation_fields.pyc
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/management/commands/update_translation_fields.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/management/commands/update_translation_fields.pyc
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/models.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/models.pyc
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/settings.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/settings.pyc
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/static/modeltranslation/css/tabbed_translation_fields.css
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/static/modeltranslation/js/force_jquery.js
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/static/modeltranslation/js/tabbed_translation_fields.js
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/translator.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/translator.pyc
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/utils.py
/home/apollov/venv/lib/python2.7/site-packages/modeltranslation/utils.pyc
Proceed (y/n)? y
   Successfully uninstalled django-modeltranslation
Downloading/unpacking django-modeltranslation
   Downloading django-modeltranslation-0.4.0.tar.gz
   Running setup.py egg_info for package django-modeltranslation

Installing collected packages: django-modeltranslation
   Running setup.py install for django-modeltranslation

Successfully installed django-modeltranslation
Cleaning up...
`

No effect either. Maybe they've released 0.4.0 in a couple of days?
13.11.2012 18:39, Jacob Magnusson пишет:

> |pip install uninstall django-modeltranslation && pip install django-modeltranslation|

**Comment by jacobsvante** [comment]
Hm I guess there's something up with my machine. I get 0.4.0-beta2 in a completely new virtualenv as well. Might be something platform specific. I'm on OS X 10.8, and I'm guessing that you're on some other nix OS (judging from your home-dir)

**Comment by apollovy** [comment]
Yep, I'm on Ubuntu 12.10. I read somewhere in docs (though I cannot find 
it for now), that pip treats -beta's as more aerly versions, than 'release'.
13.11.2012 18:44, Jacob Magnusson пишет:

**Comment by jacobsvante** [comment]
Yeah that makes sense, seems that my pip doesn't want to work that way though...

**Pull request merged**
